
---
output: rmarkdown::github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Beyond Beamer: Modern and Dynamic Presentations with R Markdown
## Emi Tanaka
### The presentation slide deck is available on Emi's website: [http://emitanaka.org/slides/rladiesSSA2020/#1](http://emitanaka.org/slides/rladiesSSA2020/#1).

### Biography

Emi Tanaka is an applied statistician whose primary interest is to develop impactful methods and tools that can be readily used by practitioners. Her research interests include mixed models and experimental designs, motivated primarily by the problems in bioinformatics and agricultural sciences. She recently joined as a lecturer at the Department of Econometrics and Business Statistics, Monash University. She is currently the Vice President of the Statistical Society of Australia Victoria Branch.

### Abstract

In this presentation, Emi takes us "Beyond Beamer: Modern and Dynamic Presentations with R Markdown". In many fields, scientific communications and publications are unimaginable without LaTeX. LaTeX, built on the TeX typesetting program, allows writing scientific documents with a markup language for structure and styling; capabilities for mathematical typesetting; ability to add cross-references and citations (though BibTeX or otherwise); and customisation through document classes, packages and macros. A particular LaTeX document class widely used for making presentation slides is Beamer. Beamer offers much of the same features as the original LaTeX in addition to special macros handy for presentation purposes and is used often by academics presenting mathematical content. Why then would we want another tool for presentation?

In this tutorial talk, Emi will talk about the capabilities and benefits of using R Markdown to make presentation slides based on the `xaringan` R-package. If you have two monitors or an extra laptop/desktop computer, then you are encouraged to try some coding yourself as you follow along with the talk.

Coding requirements: you will need to be familiar with R, have R and the xaringan & tidyverse R packages installed. It is preferable that you use RStudio IDE although not required.






