
---
output: rmarkdown::github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Workshop for Design a Personal Website with R
## Alison Hill (RStudio)
### The webcast recording can be found here: https://webcast.csiro.au/#/webcasts/rladiesworkshop.

### Event Description

Design a personal website with RStudio, R Markdown, and Hugo.

The R package blogdown (https://bookdown.org/yihui/blogdown/) makes it possible to build beautiful "out of the box" websites from within your RStudio IDE. In this workshop, we'll create and publish a website using the blogdown package and the Hugo Academic theme (https://sourcethemes.com/academic/). You'll learn how to personalize both the style and content of your site. Bring your laptop, make sure you have the RStudio IDE installed and working, and don't forget your power cord! You can view related content from a similar workshop here: https://summer-of-blogdown.netlify.com/.

Pre-Work: Please complete the prework at https://ysc-rmarkdown.netlify.com/materials/prework/. The most important bits are to make sure you have a GitHub account (with a password you know), R (>=3.6), RStudio (>=1.2), and the blogdown package.

Arrival: Please arrive at least 20 mins before the start time to sign into the Synergy building via 1 of 2 ipads and get set up for the tutorial. When prompted for who you are visiting, select either Jiali Wang or Petra Kuhnert. Please DO NOT arrive late as someone will need to get you into the building.

### Biography

Alison Hill is a Data Scientist & Professional Educator on the RStudio Education team, whose mission is to train the next million R users globally. She received her PhD in psychology and quantitative methods from Vanderbilt University. Alison is an international keynote speaker, and regularly leads workshops and develops online learning materials on topics like reproducible research, machine learning, and data visualization. She lives in Portland, Oregon with her husband and young daughter.






