
---
output: rmarkdown::github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# R Skills Workshop: R Markdown and Building Packages
## Nick Tierney and Damjan Vukcevic

### Event Description

Nick Tierney and Damjan Vukcevic will give an R skills workshop on Wednesday 3rd July. SSA Canberra has kindly offered discount registration for non-student R-Ladies members (for SSA student members the fee is $80), if she promised to give a talk this year or next year at one of the R-Ladies events. The topic of the talk can be anything related to using R at any level of proficiency. If interested, please email us to get the discount voucher!

About the workshop:
When performing data analysis, you typically need to share your insights with others. In our morning workshop, you will learn how to share and communicate your findings with yourself and others using R Markdown. As you go further on your journey with R, you will write functions that you use to perform common tasks. In the afternoon workshop, you will learn how put these together into an R package, which makes them easier to use and very easy to share.

R Markdown (morning session, 9:30am to 12:30pm), presented by Nick Tierney

For a scientific report to be completely credible, it must be reproducible. The full computational environment used to derive the results, including the data and code used for statistical analysis should be available for others to reproduce. R Markdown is a tool that allows you integrate your code, text and figures in a single file in order to make high quality, reproducible reports. A paper published with an included R Markdown file and data sets can be reproduced by anyone with a computer. After completing this course, you will know how to:
- Create your own R Markdown document
- Create figures and tables that you can reference in text, and update with - your data
- Export your R Markdown document to PDF, HTML, and Microsoft Word
- Use keyboard shortcuts to improve workflow
- Cite research articles and generate a bibliography

Building R packages (afternoon session, 1:30pm to 5pm), presented by Damjan Vukcevic

You have developed a new statistical method. Now it is time to share it with the world. The methods that actually get used in practice are those with readily available and user-friendly implementations. Writing and disseminating software is therefore a key skill for modern statisticians, one that is generally not taught widely. This course aims to fill the gap. The R software environment is widely used for statistical analyses. One of its distinguishing features is the extensive range of R ‘packages’, which anyone can write and share via the internet. This used to be an intimidating process but modern tools have made it simple.

We begin our course with how to write a very basic package, and then show how to include documentation, examples and data. Further topics include: an efficient development workflow, managing relationships between packages, sharing your packages with others, and easy ways to manage packages (finding, installing, upgrading).